server.port=${SERVER_PORT:3003}
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/orderdb}
node.service.url=${NODE_SERVICE_URL:http://localhost:3001}
python.service.url=${PYTHON_SERVICE_URL:http://localhost:3002}
